import { Roboto } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import ScrollToTop from '@/components/ScrollToTop';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  display: 'swap',
  variable: '--font-roboto',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
